### ISSUE TITLE
Issur with Vanadium

### ISSUE THREAD

**Issue by aisknab** [futo-org/voice-input#2]
The browser that comes with graphene OS is called Vanadium. 

When opening a new tab, the microphone icon is actually next to the URL bar rather than the keyboard. This still opens futo voice input so that works fine, but there is an issue. 

After recording a voice, you can clearly see that the voice records, converts to text correctly but then it doesn't paste it into the URL bar so it's not functional.

I'm unsure how to debug etc but the vanadium version is Version 117.0.5938.153.0

org.chromium.chrome
versionCode 593815332

targetSdk 34
minSdk 29

And I'm using the SDK version of futo.

Cheers.

**Comment by abb128** [comment]
Thanks for the report! It turns out that Chromium requires confidence scores in the intent completion result: https://github.com/chromium/chromium/blob/263ec6157eec0c193eaa4b27811d48f87c68a524/chrome/browser/ui/android/omnibox/java/src/org/chromium/chrome/browser/omnibox/voice/VoiceRecognitionHandler.java#L435

This was not being provided by Voice Input. I pushed a fix to the master branch and this will be fixed in the next release.
